Repository woohyuckk/nbc-outsourcing-project, pull requests merged in 2025-03, with the labels that each got.

#33 feat: 좋아요 버튼 구현
  src/components/buttons/DefaultButton.jsx
  src/components/buttons/LikeButton.jsx
  src/components/home/HomeCard.jsx
  src/components/home/HomeCardContainer.jsx
  src/libs/api/fetchData.js
  src/libs/api/likesData.js
  src/libs/api/placesData.js
  src/libs/hooks/useGetPlaces.js
  src/libs/hooks/useLikes.js
  src/libs/utils/homeUtils.js
  src/pages/Home.jsx
Labels: 💻Feature

#34 Feat/social login -- 구글 소셜로그인 기능 추가 / 로그아웃 로직 개선
  src/components/auth/AuthForm.jsx
  src/components/auth/AuthListener.jsx
  src/components/layout/Header.jsx
  src/libs/hooks/useAuth.api.js
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/stores/useAuthstore.js
Labels: 💻Feature

#36 feat: 프로필 이미지 업로드 UI 수정 및 좋아요 목록 보기 추가 구현
  package.json
  src/components/mypage/LikesSection.jsx
  src/components/mypage/ProfileForm.jsx
  src/components/mypage/ProfileImageUpload.jsx
  src/components/mypage/ProfileSection.jsx
  src/libs/api/fetchLikesData.js
  src/libs/hooks/useLikedPlaces.js
  src/pages/Mypage.jsx
  yarn.lock
Labels: 🎨Design, 📭API, 💻Feature

#37 feat/optimistic: Commnet에 Optimistic update 적용 및 UI 수정
  src/components/detail/Comment.jsx
  src/components/detail/ImageModal.jsx
  src/components/detail/PlaceCard.jsx
  src/components/detail/PlaceSection.jsx
  src/components/detail/comment/Comment.jsx
  src/components/detail/comment/CommentUserProfile.jsx
  src/components/detail/comment/CommentsSection.jsx
  src/components/detail/comment/ModifyMenu.jsx
  src/constants/queryKeyConstants.js
  src/libs/hooks/useComment.js
  src/libs/hooks/useGetPlaces.js
  src/pages/Detail.jsx
Labels: 💻Feature

#38 fix: ISSUES TEMPLATE GROUP LABEL 해제
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📃Docs

#42 Feat/social login 디버깅 완료
  src/components/auth/AuthForm.jsx
  src/stores/useAuthstore.js
Labels: 🛑Bug

#45 fix: optimistic update, 마이페이지 문제 수정
  src/components/mypage/LikesSection.jsx
  src/libs/api/fetchLikesData.js
  src/libs/api/likesData.js
  src/libs/hooks/useGetPlaces.js
  src/libs/hooks/useLikes.js
Labels: 🛑Bug

#46 feat/detail : 장소 이미지 추가및 컴포넌트 정리
  src/components/detail/ImageModal.jsx
  src/components/detail/KaKaoMap.jsx
  src/components/detail/MapOverlay.jsx
  src/components/detail/PlaceSection.jsx
  src/components/detail/comment/CommentsSection.jsx
  src/components/detail/place/PlaceInfo.jsx
  src/components/detail/place/PlaceSection.jsx
  src/libs/hooks/useComment.js
  src/pages/Detail.jsx
Labels: 🛠Refactor, 💻Feature

#47 feat: 마이페이지 리팩토링, 로딩 컴포넌트 구현
  package.json
  src/components/buttons/MyPageTapButton.jsx
  src/components/common/Loading.jsx
  src/components/mypage/MypageContent.jsx
  src/components/mypage/likes/LikeItem.jsx
  src/components/mypage/likes/LikesList.jsx
  src/components/mypage/likes/LikesSection.jsx
  src/components/mypage/profile/ProfileForm.jsx
  src/components/mypage/profile/ProfileImageUpload.jsx
  src/components/mypage/profile/ProfileSection.jsx
  src/pages/Mypage.jsx
  yarn.lock
Labels: 🛠Refactor

#53 refact/detail design : detail 페이지 design 변경
  src/components/buttons/DefaultButton.jsx
  src/components/detail/KaKaoMap.jsx
  src/components/detail/comment/Comment.jsx
  src/components/detail/comment/CommentsSection.jsx
  src/components/detail/place/ImageModal.jsx
  src/components/detail/place/PlaceInfo.jsx
  src/components/detail/place/PlaceSection.jsx
  src/components/mypage/likes/LikesSection.jsx
  src/constants/queryKeyConstants.js
  src/libs/hooks/useComment.js
  src/pages/Detail.jsx
Labels: 🎨Design

#51 Feat/toast toastify / logo 업데이트
  package.json
  public/logo.png
  src/App.jsx
  src/components/auth/AuthForm.jsx
  src/components/detail/comment/Comment.jsx
  src/components/detail/comment/CommentsSection.jsx
  src/components/layout/Header.jsx
  src/components/mypage/profile/ProfileImageUpload.jsx
  src/components/mypage/profile/ProfileSection.jsx
  src/constants/.gitkeep
  src/index.css
  src/libs/hooks/useComment.js
  src/libs/utils/.gitkeep
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/routes/Router.jsx
  yarn.lock
Labels: 🎨Design, 💻Feature

#52 feat: 장소 좋아요 목록에서 로딩 상태 처리 및 컴포넌트 리팩토링
  src/components/detail/comment/Comment.jsx
  src/components/detail/comment/CommentsSection.jsx
  src/components/detail/place/PlaceSection.jsx
  src/components/mypage/MypageContent.jsx
  src/components/mypage/likes/LikeCard.jsx
  src/components/mypage/likes/LikeItem.jsx
  src/components/mypage/likes/LikesSection.jsx
  src/components/mypage/profile/ProfileForm.jsx
  src/components/mypage/profile/ProfileImageUpload.jsx
  src/components/mypage/profile/ProfileSection.jsx
  src/pages/Detail.jsx
Labels: 🛠Refactor

#56 design: 홈 반응형 수정
  src/components/home/HomeCard.jsx
  src/components/home/HomeCardContainer.jsx
  src/components/home/SideBar.jsx
  src/pages/Home.jsx
Labels: 🎨Design
