Repository woohyuckk/nbc-outsourcing-project, pull requests merged in 2025-02, with the labels that each got.

#19 feat : 카테고리 분류 , 디테일 페이지 이동
  src/components/home/HomeCard.jsx
  src/components/home/HomeCardContainer.jsx
  src/components/home/SideBar.jsx
  src/constants/HomeConstant.js
  src/libs/api/fetchData.js
  src/libs/hooks/useGetPlaces.js
  src/libs/utils/homeUtils.js
  src/pages/Home.jsx
  src/routes/Router.jsx
Labels: 💻Feature

#20 Feat/login 현 회원가입 로직 개선
  src/libs/hooks/useAuthListener.js
  src/pages/SignUp.jsx
  src/stores/useAuthstore.js
Labels: 🛠Refactor, 💻Feature

#21 Feat/detail 패키지추가/ detail 페이지 기능 추가
  .prettierrc
  index.html
  package.json
  src/components/detail/CommentsSection.jsx
  src/components/detail/ImageModal.jsx
  src/components/detail/KaKaoMap.jsx
  src/components/detail/PlaceCard.jsx
  src/components/detail/PlaceSection.jsx
  src/components/layout/Main.jsx
  src/index.css
  src/pages/Detail.jsx
  yarn.lock
Labels: 💻Feature

#24 feat: 재사용 버튼 컴포넌트 추가
  src/components/buttons/DefaultButton.jsx
  src/components/buttons/LikeButton.jsx
  src/components/layout/Header.jsx
  src/routes/Router.jsx
Labels: 🎨Design, 💻Feature
